# Generated by Django 4.2 on 2023-04-16 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('traits', '0002_trait_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trait',
            name='pets',
        ),
    ]
